name: Verify Black Hole Canister
on:
  - push
  - workflow_dispatch
jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.5
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: npm ci && npm run setup && npm run verify

  verify-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.5
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: npm ci && npm run setup && npm run verify

  verify-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.5
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: npm ci && npm run setup && npm run verify
