name: Verify Black Hole Canister
on:
  - push
  - workflow_dispatch
jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorgenbuilder/setup-dfx@0.0.4
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: npm ci && npm run setup && npm run verify
